import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { Suspense } from 'react';
import './globals.css';

const dmSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${dmSans.className}`} suppressHydrationWarning>
        <Suspense fallback={null}>
          <div className='root-layout'>{children}</div>
        </Suspense>
      </body>
    </html>
  );
}
